[config]

[templates.hyprland]
input_path  = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook   = "hyprctl reload"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/theme'
post_hook = 'pkill -USR1 cava'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/Matugen.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.swaync]
input_path = "/home/nguyenthevinh/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "sleep 1 && swaync-client -rs"